#! /bin/sh
#------------------------------------------------------------------------------
#-- Copyright (c) 2020 TclHdl
#-- 
#-- Permission is hereby granted, free of charge, to any person obtaining a copy
#-- of this software and associated documentation files (the "Software"), to deal
#-- in the Software without restriction, including without limitation the rights
#-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#-- copies of the Software, and to permit persons to whom the Software is
#-- furnished to do so, subject to the following conditions:
#-- 
#-- The above copyright notice and this permission notice shall be included in all
#-- copies or substantial portions of the Software.
#-- 
#-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#-- SOFTWARE.
#------------------------------------------------------------------------------
#-- Project  : TclHdl
#-- Author   : Paulo Machado <pffmachado@gmail.com> 
#-- Filename : lmfree
#------------------------------------------------------------------------------
#-- File Description:
#--
#--
#--
#--
#------------------------------------------------------------------------------
#-- ChangeLog:
#--
#--
#--
#--
#------------------------------------------------------------------------------

LM_PATH=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
FEATURE=$1
LICENSE_FILE=""

LICNR=1
LICSRV=$(${LM_PATH}/lmutil lmstat | grep 'License server status:' | awk '{print $4}' | sort -R)

nr=0
for lic in $LICSRV;
do

    feature_license=$(${LM_PATH}/lmutil lmstat -c $lic -f $FEATURE | grep $FEATURE)
    if [ -z "$feature_license" ];
    then
      continue
    fi

    nr=$((nr+1))

    feature_license_issued=$(echo $feature_license | sed 's/.* (\(.*\))/\1/' | sed 's/;  /;/' | tr ";" "\n" | awk '{print $3}' | sed -n 1p)
    feature_license_used=$(echo $feature_license | sed 's/.* (\(.*\))/\1/' | sed 's/;  /;/' | tr ";" "\n" | awk '{print $3}' | sed -n 2p)
    if [ $feature_license_issued -gt $feature_license_used ];
    then
      if [ $nr -eq 1 ];
      then
                LICENSE_FILE="$lic"
      else
                LICENSE_FILE="$LICENSE_FILE:$lic"
      fi

      if [ $nr -ge $LICNR ];
      then
          break
      fi
    fi

done

echo $LICENSE_FILE
